-- Crowds: grid cells are generated by CrowdService on startup (CrowdGrid), base load comes from open data
-- (OSM places + ZTP Kraków GTFS), corrected by "Jak tłoczno?" reports and live app activity.
ALTER TABLE grid_cell ADD COLUMN transit_profile jsonb; -- 24 numbers 0..1: relative departures per hour of day

CREATE TABLE crowd_report (
    id         uuid PRIMARY KEY,
    cell_id    varchar NOT NULL REFERENCES grid_cell (id) ON DELETE CASCADE,
    user_id    uuid NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    level      smallint NOT NULL CHECK (level BETWEEN 0 AND 2), -- 0 luźno, 1 średnio, 2 tłoczno
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX crowd_report_cell_idx ON crowd_report (cell_id, created_at);
CREATE INDEX crowd_report_user_idx ON crowd_report (user_id, cell_id, created_at);

CREATE TABLE crowd_snapshot (
    cell_id    varchar NOT NULL REFERENCES grid_cell (id) ON DELETE CASCADE,
    ts         timestamptz NOT NULL,
    crowd      double precision NOT NULL,
    source_mix jsonb NOT NULL,
    PRIMARY KEY (cell_id, ts)
);
